[tox]
envlist = py313

[testenv]
deps =
  pytest
  mock
commands = pytest -v {posargs}

[testenv:flake8]
skipdist = True
usedevelop = True
deps = flake8
commands = flake8 tinkerer tinkertest

[testenv:cover]
deps =
  pytest
  coverage
basepython=python3.13
commands = pytest --cov=tinkerer {posargs}
